py_test(
  name = "python_import_test",
  srcs = ["python_import_test.py"],
  data = ['//python/bindings:mamcts.so'],
  imports = ['../../bindings'],
)

py_test(
  name = "python_import_ltl_test",
  srcs = ["python_import_ltl_test.py"],
  data = ['//python/bindings:ltl.so'],
  imports = ['../../bindings'],
)