cc_library(
    name = "mcts",
    #srcs = ["mcts_parameters.cpp"],
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_eigen_eigen//:eigen",
    ],
)
