cc_test(
    name = "comperator_test",
    srcs = ["comperator_test.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "//mvmcts",
        "@com_github_google_glog//:glog",
        "@gtest//:main",
    ],
)
