cc_library(
    name = "label_evaluators",
    srcs = glob(["*.cpp"]),
    hdrs = glob([
        "*.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//test/crossing_test:common",
    ],
)
